runtime: php55
api_version: 1

handlers:
- url: /
  application_readable: true
  static_files: static/index.html
  upload: static/index.html

- url: /resume.pdf
  application_readable: true
  static_files: static/resume.pdf
  upload: static/resume.pdf

- url: /css
  application_readable: true
  static_dir: css

- url: /js
  application_readable: true
  static_dir: js

- url: /fonts
  application_readable: true
  static_dir: fonts

- url: /images
  application_readable: true
  static_dir: images

- url: /php/contact.php
  script: php/contact.php
